### ISSUE TITLE
units for snow depth values

### ISSUE THREAD

**Issue by aaarendt** [communitysnowobs/mountainhub-api#9]
The API currently does not return any information on snow depth units, and I noted that we don't include that information anywhere in our documentation. Could this be something that gets returned during the API call? Or should we just make it clear in the README.md?

**Comment by emiliom** [comment]
The units (meters) are mentioned in the README.md file; see the last sentence in the "Usage" section. Can you suggest a way to make it more prominent?

I see that the docstring for the `snow_data` function doesn't mention the units, though. That should be changed. How about "Retrieves snow data in meters from the MountainHub API."?

**Comment by aaarendt** [comment]
OK, I see the units now. But I think the units must be cm, based on values I'm returning in my script.

I think listing out the returned parameters as separate bullets, as for the keyword args above it, might improve readability? Also the returned pandas dataframe has additional content such as `author_name` and `obs_type`. Should we include those in the list too?

I agree with updating the docstring as suggested. Happy to make a PR for all these changes.

**Comment by emiliom** [comment]
> Happy to make a PR for all these changes.

That would be great! I'll tackle your other PR (#8), hopefully today.

**Comment by aaarendt** [comment]
Changes made in PR (#10), closing.
